name = "Quilted Create"
author = "Rain"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a3c7d1a83ba1c2bfbe4dd28470f88e0a5fc235777e093168bdad3d617f98d2ab"

[versions]
minecraft = "1.19.2"
quilt = "0.19.0-beta.13"

[options]
acceptable-game-versions = ["1.19"]
