name = "Quilted Create"
author = "Rain"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e551dcb713e95075a6f76ac8d1280844872f5079a7d2928777c0ee048b13c9e2"

[versions]
minecraft = "1.19.2"
quilt = "0.19.0-beta.13"

[options]
acceptable-game-versions = ["1.19"]
